### PR TITLE
Changes are complete for signup form

### PR DESCRIPTION
**Pull request by SwaroopSambhayya**
I have made changes, now user won't be able to move further steps without entering information in previous steps except optional and also link validation is complete as requested @adityamahajan-io

### CODE REVIEW

**Comment by SwaroopSambhayya** [comment]
this is regrading issue #73

**Comment by adityamahajan-io** [comment]
Hey! We cannot merge your PR without reviewing changes on Github Pages (see 4th point in contributing.md)
Send in your GitHub Pages URL so we can review and merge!

**Review by adityamahajan-io — CHANGES_REQUESTED** [review]
Github Pages URL required to review changes. (4th point in contributing.md)

**Comment by adityamahajan-io** [comment]
Also resolve any conflicts with the master branch. We have updated register.html to show lables on every input filed. Pull the latest changes and submit your URL 👍

**Comment by SwaroopSambhayya** [comment]
Resolved Conflicts this is Github page url
https://swaroopsambhayya.github.io/skill-board/

**Review by adityamahajan-io — APPROVED** [review]

**Comment by adityamahajan-io** [comment]
Great work 👍  Thanks for contributing!

**Pull request merged**
