### PR TITLE
[Added]: Back button in profile page

### PR DESCRIPTION
**Pull request by SuvamPrasd**
According to the issue, I have added a back button on the profile page. With the help of the back button, the user can navigate to the previous history page.

### CODE REVIEW

**Review by adityamahajan-io — CHANGES_REQUESTED** [review]
We need to review your changes on a GitHub pages URL. 4th point in contributing.md.
Mention your URL here so we can review your changes before merging.

**Comment by SuvamPrasd** [comment]
https://suvamprasd.github.io/skill-board/.

**Review by adityamahajan-io — APPROVED** [review]

**Comment by adityamahajan-io** [comment]
@SuvamPrasd Looks great! Merging now :)

**Comment by SuvamPrasd** [comment]
Thank you

**Pull request merged**
