### PR TITLE
added floating labels to register form

### PR DESCRIPTION
**Pull request by muhammadev**

### CODE REVIEW

**Comment by muhammadev** [comment]
can you please review my PR and tell me if there is anything wrong?
@adityamahajan-io

**Comment by adityamahajan-io** [comment]
@muhammadev There seems to be a conflict with the master branch. Use 'git pull upstream master' and resolve the conflict.
In case of any doubts, refer to the contributing.md file for all the instructions.
Also, please add the same floating labels on updateProfile.html as well!

**Comment by muhammadev** [comment]
I added the floating labels to updateProfile.html
can you review it please? I need at least one of those choices for accepting my PR on Hacktoberfest:
> A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it.

@adityamahajan-io

**Review by adityamahajan-io — APPROVED** [review]

**Comment by adityamahajan-io** [comment]
Looks great @muhammadev 👍 Thanks for contributing 😄

**Pull request merged**
